### ISSUE TITLE
Add voice commands for choosing/switching Pokémon

### ISSUE THREAD

**Issue by AdamJonsson** [AdamJonsson/GamingSpeechController#3]
- [x] Add an internal state/context for the currently chosen pokemon
- [x] Skip confirm dialogs wheen choosing/switching Pokémons

**Comment by ellaklara** [comment]
Not cool, @AdamJonsson! The plural of Pokémon is Pokémon, not Pokémons :((((
just kidding ;)

**Comment by AdamJonsson** [comment]
It is now fixed, closing #11
